syntax = "proto3";

package tenon.cp.v1;

import "daemon-message.proto";

message ApplyManifestRequest {
  string manifest = 1;
}

message ApplyManifestResponse {
  bool accepted = 1;
  tenon.daemon.v1.ResourceId active_plan = 2;
  ApplyManifestMode mode = 3;
  string message = 4;
}

enum ApplyManifestMode {
  APPLY_MANIFEST_MODE_UNSPECIFIED = 0;
  APPLY_MANIFEST_MODE_STARTED = 1;
  APPLY_MANIFEST_MODE_HOT_RELOAD = 2;
  APPLY_MANIFEST_MODE_REJECTED_RESTART_REQUIRED = 3;
  APPLY_MANIFEST_MODE_REJECTED_WORKER_ERROR = 4;
  APPLY_MANIFEST_MODE_REJECTED_INVALID_MANIFEST = 5;
}

message PutResourceRequest {
  tenon.daemon.v1.Resource resource = 1;
}

message PutResourceResponse {
  bool accepted = 1;
  tenon.daemon.v1.ResourceId id = 2;
  ApplyManifestMode mode = 3;
  string message = 4;
  repeated tenon.daemon.v1.ResourceId resource_ids = 5;
}

message ReviseResourceRequest {
  tenon.daemon.v1.ResourceId pipeline_id = 1;
  tenon.daemon.v1.ResourceId previous_resource_id = 2;
  tenon.daemon.v1.Resource new_resource = 3;
}

message ReviseResourceResponse {
  bool accepted = 1;
  tenon.daemon.v1.ResourceId revised_pipeline_id = 2;
  string message = 3;
  tenon.daemon.v1.ResourceId revised_resource_id = 4;
  repeated tenon.daemon.v1.ResourceId resource_ids = 5;
}

message ApplyResourceRequest {
  tenon.daemon.v1.ResourceId pipeline_id = 1;
}

message ApplyResourceResponse {
  bool accepted = 1;
  tenon.daemon.v1.ResourceId active_pipeline_id = 2;
  ApplyManifestMode mode = 3;
  string message = 4;
}

message GetPipelineRequest {
  string name = 1;
}

message GetPipelineResponse {
  bool found = 1;
  string manifest = 2;
  string message = 3;
}

message ControlPlaneEnvelope {
  oneof payload {
    ApplyManifestRequest apply_manifest = 1;
    ApplyManifestResponse apply_manifest_response = 2;
    GetPipelineRequest get_pipeline = 3;
    GetPipelineResponse get_pipeline_response = 4;
    PutResourceRequest put_resource = 6;
    PutResourceResponse put_resource_response = 7;
    ReviseResourceRequest revise_resource = 8;
    ReviseResourceResponse revise_resource_response = 9;
    ApplyResourceRequest apply_resource = 10;
    ApplyResourceResponse apply_resource_response = 11;
  }
}
