syntax = "proto3";

package tenon.cp.v1;

import "daemon-message.proto";

message ApplyManifestRequest {
  string manifest = 1;
}

message ApplyManifestResponse {
  bool accepted = 1;
  tenon.daemon.v1.ResourceId active_plan = 2;
  ApplyManifestMode mode = 3;
  string message = 4;
}

enum ApplyManifestMode {
  APPLY_MANIFEST_MODE_UNSPECIFIED = 0;
  APPLY_MANIFEST_MODE_STARTED = 1;
  APPLY_MANIFEST_MODE_HOT_RELOAD = 2;
  APPLY_MANIFEST_MODE_REJECTED_RESTART_REQUIRED = 3;
  APPLY_MANIFEST_MODE_REJECTED_WORKER_ERROR = 4;
  APPLY_MANIFEST_MODE_REJECTED_INVALID_MANIFEST = 5;
}

message ApplyDeploymentRequest {
  tenon.daemon.v1.DeploymentPlan plan = 1;
}

message ApplyDeploymentResponse {
  bool accepted = 1;
  tenon.daemon.v1.ResourceId active_plan = 2;
  ApplyManifestMode mode = 3;
  string message = 4;
}

message GetPipelineRequest {
  string name = 1;
}

message GetPipelineResponse {
  bool found = 1;
  string manifest = 2;
  string message = 3;
}

message ControlPlaneEnvelope {
  oneof payload {
    ApplyManifestRequest apply_manifest = 1;
    ApplyManifestResponse apply_manifest_response = 2;
    GetPipelineRequest get_pipeline = 3;
    GetPipelineResponse get_pipeline_response = 4;
    ApplyDeploymentRequest apply_deployment = 6;
    ApplyDeploymentResponse apply_deployment_response = 7;
  }
}
